import './globals.css'
import styles from './layout.module.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <head/>
      <body>
        <header className={styles.header}>
          <h1>header nav bar</h1>
          <nav className={styles.nav}>
            <a href='/products'>Products</a>
            <a href='/contact'>Contact</a>
            <a href='/about'>about</a>
          </nav>
        </header>
        {children}
      </body> 
    </html>
  )
}
